### ISSUE TITLE
Randomizer not working for me

### ISSUE THREAD

**Issue by TimoV2003** [Aldo796/BDSP-Randomizers#45]
Dumped the files through yuzu, copied the romfs to the randomizer file and after that trying to randomize gives me this error.

Randomizer settings:
Starters
Encounters
Safari
Underground
Trainers
Shops
TM's + compa
Field items
movesets
60 fps mod

RomFS Directory set to C:/Users/timor/Downloads/bdsp-randomizer210-1/mods/emulatorRandomized/romfs\Data
Output folder set to C:\Users\timor\Downloads\bdsp-randomizer210-1\mods
Randomizing Starters!
ERROR: english not found 
An Error has occured: 
Traceback (most recent call last):
  File "main.py", line 54, in buttonClicked
  File "C:\Users\timor\Downloads\bdsp-randomizer210-1\lib\Randomizers\Starters.py", line 129, in RandomizeStarters
    for obj in env.objects:
AttributeError: 'NoneType' object has no attribute 'objects'

**Comment by TimoV2003** [comment]
Already found out what I did wrong. Copied the romfs to the path where romfs needs to be empty
