### ISSUE TITLE
error no matter what I try to randomize

### ISSUE THREAD

**Issue by BruceBruce19** [Aldo796/BDSP-Randomizers#46]
Randomizing Starters!
ERROR: english not found 
An Error has occured: 
Traceback (most recent call last):
  File "main.py", line 54, in buttonClicked
  File "C:\Users\Bruce\Desktop\bdsp-randomizer210-1\lib\Randomizers\Starters.py", line 129, in RandomizeStarters
    for obj in env.objects:
AttributeError: 'NoneType' object has no attribute 'objects'

You can replace starters with any of the selections due to thats what it is giving me no matter the selection

**Comment by Ai0796** [comment]
What's the romfs folder you're selecting

**Comment by BruceBruce19** [comment]
i used the nxdumptool and then transferred the romfs and exefs folders and
then used that romfs file, i tried both shining pearl and brilliant diamond
and still get the same results

**Comment by BruceBruce19** [comment]
I apologize as I just figured out what I was doing wrong and that is where
I was putting the dumped folders.

thank you

**Comment by simonrule** [comment]
im having same issue i dumped the game using nxdumptool
so what i did is this
create main folder inside of it is romfs and exfs i put the required files in each folder.

results:

RomFS Directory set to C:/Users/simon/Desktop/briliant
Output folder set to C:\Users\simon\Downloads\Compressed\exe.win-amd64-3.10\mods
Randomizing Starters!
ERROR: english not found 
An Error has occured: 
Traceback (most recent call last):
  File "main.py", line 54, in buttonClicked
  File "C:\Users\simon\Downloads\Compressed\exe.win-amd64-3.10\lib\Randomizers\Starters.py", line 129, in RandomizeStarters
    for obj in env.objects:
AttributeError: 'NoneType' object has no attribute 'objects'

**Comment by BruceBruce19** [comment]
You have to play the game and make a save file that can be anywhere (right
after the first cut scene if you want). That's the resolution I found as
those dumped files won't have anything in them from my understanding unless
you have a save file.
