### ISSUE TITLE
2.4 Crashing on Starters

### ISSUE THREAD

**Issue by Hannike** [Aldo796/BDSP-Randomizers#6]
Hey, 

Version 2.4 is crashing whenever I choose Starters and select the romfs. The rest is randomized with no issues, but Starters makes the application crash without even throwing an error message. Version 2.3 is working without issues including Starters, but 2.4 is not. Any ideas why? 

Thanks in advance,
Nickk

**Comment by Ai0796** [comment]
Try using the newest version of the randomizer, if it still doesn't work, post the error message

**Comment by Hannike** [comment]
The error message it returns is:

An Error has occured: 
Traceback (most recent call last):
  File "main.py", line 32, in buttonClicked
  File "D:\Users\moald\OneDrive\Projects\BDSP-Randomizers\Randomizers\Starters.py", line 131, in RandomizeStarters
  File "D:\Users\moald\OneDrive\Projects\BDSP-Randomizers\Randomizers\Starters.py", line 109, in colorPokemon
  File "D:\Users\moald\OneDrive\Projects\BDSP-Randomizers\Randomizers\Starters.py", line 92, in getPokemonColor
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 904: illegal multibyte sequence

**Comment by Hannike** [comment]
I figured it out. I fixed it by changing my system language which was originally in Chinese to English. My guess is that you didn't specify the decoding format as utf-8 after rewriting the code? Thanks for the help anyway, problem solved, and great work. :)
